# Generated by Django 4.1.4 on 2022-12-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv",
                    models.FileField(upload_to="csvfiles/", verbose_name="CSV File"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Candlestick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banknifty",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Bank Nifty"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Time")),
                (
                    "open_value",
                    models.FloatField(blank=True, null=True, verbose_name="Open"),
                ),
                ("high", models.FloatField(blank=True, null=True, verbose_name="High")),
                ("low", models.FloatField(blank=True, null=True, verbose_name="Low")),
                (
                    "close",
                    models.FloatField(blank=True, null=True, verbose_name="Close"),
                ),
                (
                    "volume",
                    models.FloatField(blank=True, null=True, verbose_name="Volume"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "csv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candlestick",
                        to="MainApp.csvfile",
                        verbose_name="CSV File",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
