# Generated by Django 4.1.4 on 2022-12-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="timeframe",
            field=models.IntegerField(blank=True, null=True, verbose_name="Timeframe"),
        ),
    ]
