# Generated by Django 4.1.4 on 2022-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0004_alter_csvfile_csv_file_alter_csvfile_timeframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candlestick",
            name="date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="candlestick",
            name="time",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Time"
            ),
        ),
    ]
