# Generated by Django 4.1.4 on 2022-12-14 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0005_alter_candlestick_date_alter_candlestick_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="json_file",
            field=models.FileField(
                blank=True,
                help_text="Please upload only .json file",
                null=True,
                upload_to="jsonfiles/",
                validators=[django.core.validators.FileExtensionValidator(["json"])],
                verbose_name="JSON File",
            ),
        ),
    ]
